### ISSUE TITLE
Hi is there weight file available for MPII

### ISSUE THREAD

**Issue by safemotion-admin** [stefanopini/simple-HigherHRNet#1]
I tried and it is working. How can I try with MPII key annotations? I think it needs a proper weights for MPII shaped pose estimation

**Comment by stefanopini** [comment]
Hi @safemotion 
Unfortunately, the HigherHRNet authors have released weights pre-trained only on COCO and ImageNet (as you can see [here](https://drive.google.com/drive/folders/1bdXVmYrSynPLSk5lptvgyQ8fhziobD50)).

If you need MPII joint annotations, you can use the previous model [simple-HRNet](https://github.com/stefanopini/simple-HRNet).
For that network, official weights pre-trained on MPII have been released.
