### ISSUE TITLE
tensorrt

### ISSUE THREAD

**Issue by chh7411898** [stefanopini/simple-HigherHRNet#10]
Did you try to convert this into tensorrt？

**Comment by stefanopini** [comment]
No, I didn't, but any contributions are welcome!
Please consider sharing the results here if you manage to convert it in tensorrt.

**Comment by gpastal24** [comment]
#14 
I have added TRT support for HigherHRNet. I have used the yolov5 conversion function since  torch2trt was throwing memory error.
It works only on the w32_512 weights

**Comment by stefanopini** [comment]
Amazing, thanks a lot for the contribution!
I will review the PR in the next weeks and consider merging it into the master branch

**Comment by gpastal24** [comment]
OK , thank you I have made some improvements to the code in order to be better understood.

**Comment by stefanopini** [comment]
Hi @gpastal24 , unfortunately I didn't have the time to look into this the last two week.
I will try to review it by the end of this week, apologies for the waiting

**Comment by gpastal24** [comment]
Hi @stefanopini, don't worry about it, I am not in a hurry. Thanks for letting me know :)

**Comment by stefanopini** [comment]
Hi @gpastal24 ! As mentioned in #14 I merged your PR that adds the support to TensorRT using yolov5 to a new branch `tensorrt`. Thanks a lot for the help with the code!

I'm now working on the PR #15 to clean up the code a bit, update the documentation (and hopefully add a link to a working example on colab) and then merge it into the master branch.
I'll let you know when everything is ready, happy to have the pr reviewed by you if you're available.

@chh7411898 the documentation is not there yet, but you can use the tensorrt convertor already from the branch `tensorrt`! Just follow the instruction posted [here](https://github.com/stefanopini/simple-HigherHRNet/pull/14#issuecomment-1304895434)

**Comment by stefanopini** [comment]
TensorRT support has been merged into master! Closing
