### ISSUE TITLE
HRnet and HigherHRnet compare

### ISSUE THREAD

**Issue by positive666** [stefanopini/simple-HigherHRNet#12]
Hi, thanks for sharing, I can understand the reasoning is slow due to the post processing complexity, but isn’t this model an updated version of HRNET? Previous approaches to detection and pose estimation have been used to infer key points for multiple people, and it is not clear why this is not as effective as HRNET

**Comment by stefanopini** [comment]
Hi! Yes, Higher-HRNet was presented after HRNet, but they use two different approaches (bottom-up vs top-down) and thus compare with different sets of competitors in the papers.
If you look at the overall accuracy though, HRNet is still more precise that HigherHRNet, even if it relies on the detections of a person detector.
If you are interested in further insights, I suggest to contact the authors of the papers.

**Comment by positive666** [comment]
> Hi! Yes, Higher-HRNet was presented after HRNet, but they use two different approaches (bottom-up vs top-down) and thus compare with different sets of competitors in the papers. If you look at the overall accuracy though, HRNet is still more precise that HigherHRNet, even if it relies on the detections of a person detector. If you are interested in further insights, I suggest to contact the authors of the papers.

Thank you for your response
