### ISSUE TITLE
.csv file

### ISSUE THREAD

**Issue by Geng17** [stefanopini/simple-HigherHRNet#13]
Hello,What is the meaning of each parameter in the.csv file? If you have time, I hope you can answer this question.thank you

**Comment by stefanopini** [comment]
Hi @Geng17 , you can find that information here
https://github.com/stefanopini/simple-HigherHRNet/blob/59ece4a24c24cc6947ceb23f49f1a413c8837bfd/scripts/extract-keypoints.py#L65-L73

Feel free to re-open the issue if that doesn't answer your question or have any other questions.
