### ISSUE TITLE
RuntimeError: [CamGear:ERROR] :: Source is invalid, CamGear failed to initialize stream on this source!

### ISSUE THREAD

**Issue by genkihoshino** [stefanopini/simple-HigherHRNet#17]
Hi, sorry for asking so many juvenile questions.
When I run `!python scripts/live-demo.py --camera_id 0` in Googlecolaboratory, I get `RuntimeError: [CamGear:ERROR] :: Source is invalid, CamGear failed to initialize stream on this source!`
The webcam is recognized on GoogleCoraboratory.
I would be glad to know how to solve this problem.
Thank you in advance.

**Comment by stefanopini** [comment]
Hi @genkihoshino , unfortunately it is not currently possible to open the webcam using OpenCV on Google Colab.

You can try editing the live demo script to open the webcam using Colab-compatible methods, e.g. see [here](https://stackoverflow.com/questions/54389727/opening-web-camera-in-google-colab).
Alternatively, you can record a video and run the script on that or install the repository on your local machine.

**Comment by genkihoshino** [comment]
Thanks for your answer.
Understood, I will try to edit the live_demo script so that I can run it.

**Comment by stefanopini** [comment]
If you find a working solution, please remind that contributions are more than welcome 🙂 
Feel also free to re-open the issue if you need further help.
