### ISSUE TITLE
Error when it isnt any person on image

### ISSUE THREAD

**Issue by garipovazamat** [stefanopini/simple-HigherHRNet#4]
Hello. Thank you for very useful model.
 I get the error 
> expected a non-empty list of Tensors

when I try to predict pose on image without any person. When person is on it I have successfull estimation.

**Comment by stefanopini** [comment]
Hi!
I should have fixed it in the latest commit.
Could you give it a try?

**Comment by garipovazamat** [comment]
Yes. Now it works. Thank you!
