### ISSUE TITLE
Extract keypoints in csv file

### ISSUE THREAD

**Issue by jellyfish1456** [stefanopini/simple-HigherHRNet#8]
Hi~
Thank you for the code implementation

Is live_demo.py has the function of generating keypoints in csv file?
Thank you!

**Comment by stefanopini** [comment]
Hi!
Currently, live_demo.py can save the keypoints only in compressed numpy format with the option `--extract_pts` (credits: #6 ).

If you look at the [simple-HRNet](https://github.com/stefanopini/simple-HRNet) repo, the script `extract-keypoints.py` can save the keypoints in csv or json format.

I'll try to add a similar script in this repository in the next days.
In the meantime, you can use [simple-HRNet](https://github.com/stefanopini/simple-HRNet) or save the keypoints in numpy format and convert them in csv afterwards.

**Comment by stefanopini** [comment]
Done! Please let me know if you encounter any issue using the script `extract-keypoints.py`
